services:
  db:
    image: mysql:8.0
    container_name: blog_api_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - crediwallet_db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysql", "-h", "db", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}", "-e", "SELECT 1"]
      interval: 30s
      timeout: 10s
      retries: 5


  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: api_backend
    restart: always
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    # depends_on:
    #   - db
    #   - redis
    #   - celery
  
  # redis:
  #   image: redis:alpine
  #   ports:
  #     - "6379:6379"
  #   healthcheck:
  #     test: ["CMD", "redis-cli", "ping"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  # celery:
  #   build: .
  #   command: celery -A blogapi worker --loglevel=info
  #   depends_on:
  #     - redis
  #     - db
  #   volumes:
  #     - .:/code
  
  # celery-beat:
  #   build: .
  #   command: celery -A blogapi beat --loglevel=info
  #   depends_on:
  #     - redis
  #     - db
  #   volumes:
  #     - .:/code

volumes:
  crediwallet_db_data: